language: python

sudo: false

python:
  - "2.7"
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
  - "pypy"
  - "pypy3"
  - "nightly"

install:
  - pip install --upgrade pip pytest setuptools
  - pip install --use-feature=2020-resolver -r tests/requirements.txt

script:
  - pytest

after_success:
  - coverage combine
  - coveralls

notifications:
  email: false
